In [6]:
import numpy as np

np.__version__

'1.15.0'

In [8]:
create_list = list(range(10))

def print_item(l):
    for item in l:
        print(type(item))
        

print_item(create_list)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [11]:
list_hetrogeneous = [1, "2", "A", 3, {"A" :3, "B":4}, 9, (10, 20, 30, 40), True]

print_item(list_hetrogeneous)

<class 'int'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'dict'>
<class 'int'>
<class 'tuple'>
<class 'bool'>


In [12]:
np.array([[1, 2, 3],
         ["A", "B", "C"]])

array([['1', '2', '3'],
       ['A', 'B', 'C']], dtype='<U21')

In [17]:
np.zeros(5, dtype='int')

np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.random.seed(10)

x = np.random.normal(0, 1, (5,5))
x
x.shape

(5, 5)

In [21]:
x = np.array(["A", "B", "C", "D", "E", "F", "G"])

In [25]:
x = np.arange(10,30)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [26]:
x[ : : -1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [27]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array(['A','B', 'C'])

np.concatenate([arr_1, arr_2, arr_3])

array(['1', '2', '3', '4', '5', '6', 'A', 'B', 'C'], dtype='<U21')

In [28]:
matrix = np.array([["I", "Love", "ML"],["not", "you", "girl"]])
print(matrix)
np.concatenate([matrix, matrix])

[['I' 'Love' 'ML']
 ['not' 'you' 'girl']]


array([['I', 'Love', 'ML'],
       ['not', 'you', 'girl'],
       ['I', 'Love', 'ML'],
       ['not', 'you', 'girl']], dtype='<U4')

In [30]:
concatenated_matrix_axis_0 = np.concatenate([matrix, matrix],axis=0)

print(concatenated_matrix_axis_0)

print (" size of concatenated_matrix_axis_0 = ", concatenated_matrix_axis_0.shape)

[['I' 'Love' 'ML']
 ['not' 'you' 'girl']
 ['I' 'Love' 'ML']
 ['not' 'you' 'girl']]
 size of concatenated_matrix_axis_0 =  (4, 3)


In [31]:
concatenated_matrix_axis_1 = np.concatenate([matrix, matrix],axis=1)

print(concatenated_matrix_axis_1)

print ("size of concatenated_matrix_axis_1 =", concatenated_matrix_axis_1.shape)

[['I' 'Love' 'ML' 'I' 'Love' 'ML']
 ['not' 'you' 'girl' 'not' 'you' 'girl']]
size of concatenated_matrix_axis_1 = (2, 6)


In [32]:
x = np.array([9, 10, 11])
matrix = np.array([[12, 13, 14],[15, 16, 17]])
vstack_example = np.vstack([x, matrix])

print(vstack_example)
print("Shape of stacked array:", vstack_example.shape)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Shape of stacked array: (3, 3)


In [33]:
z = np.array([[0], [0]])
hstack_example = np.hstack([matrix, z])

print(hstack_example)
print("Shape of stacked array:", hstack_example.shape)

[[12 13 14  0]
 [15 16 17  0]]
Shape of stacked array: (2, 4)


In [41]:
arr = np.arange(12)

np.split(arr,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [56]:
arr2 = np.random.randint(10,size=(10,10))

np.vsplit(arr2,2)

[array([[7, 5, 7, 9, 6, 7, 5, 4, 9, 9],
        [9, 1, 9, 5, 3, 4, 3, 0, 4, 2],
        [0, 5, 9, 6, 4, 2, 7, 9, 8, 9],
        [7, 9, 0, 4, 8, 7, 9, 2, 7, 0],
        [7, 4, 9, 2, 8, 8, 8, 1, 8, 1]]),
 array([[4, 3, 5, 5, 2, 6, 6, 9, 4, 4],
        [0, 8, 9, 2, 8, 5, 8, 0, 9, 7],
        [7, 4, 0, 3, 7, 4, 4, 1, 4, 4],
        [2, 0, 1, 6, 5, 0, 2, 0, 9, 4],
        [3, 8, 7, 6, 9, 8, 8, 7, 9, 7]])]