In [1]:
import numpy as np
import time

In [2]:
data = [6, 7.5, 8, 0, 1]
arr = np.array(data)
print(arr)


[6.  7.5 8.  0.  1. ]


In [3]:
matrix = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr = np.array(matrix)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
arr.ndim

2

In [5]:
arr.shape

(2, 4)

In [6]:
arr.dtype

dtype('int64')

In [8]:
zero_arr = np.zeros(5)
print(zero_arr)

[0. 0. 0. 0. 0.]


In [9]:
emp_arr = np.empty((2,4))
print(emp_arr)   

[[0.00000000e+000 6.92755318e-310 6.92755583e-310 5.39492808e-317]
 [5.39495970e-317 6.92754733e-310 3.16202013e-322 6.92755587e-310]]


In [12]:
arr1 = np.array(np.random.randn(100000))
arr2 = np.array(np.random.randn(100000))
new_arr = np.empty(100000)
new_arr

array([ 1.39366828e-316,  1.46633150e-316,  0.00000000e+000, ...,
        1.12200246e+000, -1.14369901e-002, -1.41233164e+000])

In [13]:
start_time = time.time()
for i in range(100000):
    new_arr[i] = arr1[i]*arr2[i]
end_time = time.time()
print((end_time - start_time)*1000)    // 10^-3 sec

62.552690505981445


In [14]:
start = time.time()
mul_arr = arr1 * arr2
end = time.time()
print((end - start)*1000)     // Great time difference (Optimized numpy mult)  vectorised mult

0.5993843078613281


In [15]:
sub_array = np.empty(100000)
start_time = time.time()
for i in range(100000):
    new_arr[i] = arr1[i]-arr2[i]
end_time = time.time()
print((end_time-start_time)*1000)

65.5374526977539


In [16]:
start_time = time.time()
sub_array_vec = arr1 - arr2
end_time = time.time()
print((end_time-start_time)*1000)

0.9307861328125


In [27]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,0,1,1])
print(1.0/arr1)          # reciprocal
print(arr1 ** 0.5)         # exponent
print(np.sqrt(arr1)) 
print(np.exp(arr1))  

[1.         0.5        0.33333333 0.25      ]
[1.         1.41421356 1.73205081 2.        ]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [31]:
mat1 = np.random.randn(100, 100)
mat2 = np.random.randn(100, 1000)

res = np.empty((100, 1000))
# regular matrix multiplication
start = time.time()
# iterate through rows of X
for i in range(len(mat1)):
   # iterate through columns of Y
   for j in range(len(mat2[0])):
       # iterate through rows of Y
       for k in range(len(mat2)):
            res[i][j] += mat1[i][k] * mat2[k][j]
end = time.time()
print((end-start)*1000)

12577.588558197021


In [32]:
start = time.time()
result = np.matmul(mat1, mat2)
end = time.time()
print((end-start)*1000)

10.098695755004883
